package br.ufmg.engsoft.reprova.model;

import java.util.Objects;

/**
 * The person type.
 */
public class Person {
  /**
   * The id of the person.
   * When null, the id will be automatically generated by the database.
   */
  public final String id;
  /**
   * The theme of the person. Mustn't be null nor empty.
   */
  public final String name;
  /**
   * The description of the person. Mustn't be null nor empty.
   */
  public final String email;
  /**
   * The statement of the person. May be null or empty.
   */
  public final String password;


  /**
   * Builder for Person.
   */
  public static class Builder {
    protected String id;
    protected String name;
    protected String email;
    protected String password;

    public Builder id(String id) {
      this.id = id;
      return this;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder email(String email) {
      this.email = email;
      return this;
    }

    public Builder password(String password) {
      this.password = password;
      return this;
    }

    /**
     * Build the person.
     * @throws IllegalArgumentException  if any parameter is invalid
     */
    public Person build() {
      if (name == null)
        throw new IllegalArgumentException("name mustn't be null");

      if (name.isEmpty())
        throw new IllegalArgumentException("name mustn't be empty");

      if (email == null)
        throw new IllegalArgumentException("email mustn't be null");

      if (email.isEmpty())
        throw new IllegalArgumentException("email mustn't be empty");
      
      if (password == null)
        throw new IllegalArgumentException("password mustn't be null");

      if (password.isEmpty())
        throw new IllegalArgumentException("password mustn't be empty");

      return new Person(
        this.id,
        this.name,
        this.email,
        this.password
      );
    }
  }

  /**
   * Protected constructor, should only be used by the builder.
   */
  protected Person(
    String id,
    String name,
    String email,
    String password
  ) {
    this.id = id;
    this.name = name;
    this.email = email;
    this.password = password;
  }

  /**
   * Equality comparison.
   * Although this object has an id, equality is checked on all fields.
   */
  @Override
  public boolean equals(Object obj) {
    if (obj == this)
      return true;

    if (!(obj instanceof Person))
      return false;

    var person = (Person) obj;

    return this.id.equals(person.id)
        && this.name.equals(person.name)
        && this.email.equals(person.email)
        && this.password.equals(person.password);
  }


  @Override
  public int hashCode() {
    return Objects.hash(
      this.id,
      this.name,
      this.email,
      this.password
    );
  }


  /**
   * Convert a Person to String for visualization purposes.
   */
  @Override
  public String toString() {
    var builder = new StringBuilder();

    builder.append("Person:\n");
    builder.append("  id: " + this.id + "\n");
    builder.append("  name: " + this.name + "\n");
    builder.append("  email: " + this.email + "\n");
    builder.append("  password: " + this.password + "\n");

    return builder.toString();
  }
}

